// src/items/Wire.tsx
import anime from "animejs"
import { themeBlack, themeRed, wireChipConnectorColor } from "../constants"
import { useEffect, useRef, useState } from "react"

export interface WireProps {
  pathOn: string,
  pathOff: string,
  circleCx?: number,
  circleCy?: number,
  wireOn: boolean,
  onClickFn: any
}

export const Wire = ({ pathOn, pathOff, circleCx, circleCy, wireOn, onClickFn }: WireProps) => {

  const animateWirePathRef = useRef(null)
  const [firstRender, setFirstRender] = useState(true)

  useEffect(() =>  {
    if (!firstRender) {
      anime({
        targets: animateWirePathRef.current,
        strokeDashoffset: [anime.setDashoffset, 0],
        easing: 'easeInOutSine',
        duration: 1000,
        delay: 0
      })
    }
    setFirstRender(false)
  }, [wireOn])
  
  return (
    <svg onClick={() => onClickFn()} overflow={'visible'}>
      { wireOn ? (
          <>
            <path
              d={pathOn}
              style={{fill: 'none', stroke: themeBlack, strokeWidth: "12", borderRadius: "12px", zIndex: 2}}
            />
            <path ref={animateWirePathRef}
              d={pathOn}
              style={{fill: 'none', stroke: themeRed, strokeWidth: "12", borderRadius: "12px", zIndex: 1, cursor: 'pointer'}}
            />
          </>
        ) : (
          <>
            <path
              d={pathOff}
              style={{fill: 'none', stroke: themeRed, strokeWidth: "12", borderRadius: "12px", zIndex: 1}}
            />
            <path ref={animateWirePathRef}
              d={pathOff}
              style={{fill: 'none', stroke: themeBlack, strokeWidth: "13", borderRadius: "12px", zIndex: 2, cursor: 'pointer'}}
            />
          </>
        )}
        { (circleCx && circleCy) &&
          (<circle fill={wireChipConnectorColor} cx={circleCx} cy={circleCy} r={10}></circle>)
        }
    </svg>
  )
}

// vue/tech-course-graphics/src/components/items/Wire.vue
<script setup lang="ts">
import { ref, watch, nextTick } from 'vue'
import anime from 'animejs'
import { themeBlack, themeRed } from '../../constants'

interface WireProps {
  pathOn: string
  pathOff: string
  isOn: boolean
  onClickFn?: () => void
  delay?: number
}

const props = defineProps<WireProps>()

const redPathRef = ref<SVGPathElement | null>(null)
const blackPathRef = ref<SVGPathElement | null>(null)

watch(() => props.isOn, async (newVal, oldVal) => {
  await nextTick()

  const animate = (el: SVGPathElement | null) => {
    if (!el) return
    const length = el.getTotalLength()
    el.setAttribute('stroke-dasharray', `${length}`)
    el.setAttribute('stroke-dashoffset', `${length}`)
    anime({
      targets: el,
      strokeDashoffset: [length, 0],
      duration: 1000,
      easing: 'easeInOutSine',
      delay: props.delay || 0
    })
  }

  if (newVal && redPathRef.value) {
    animate(redPathRef.value)
  }

  if (!newVal && blackPathRef.value) {
    animate(blackPathRef.value)
  }
})
</script>

<template>
  <svg @click="props.onClickFn?.()" overflow="visible">
    <g v-if="props.isOn">
      <!-- Black base path (underlay) -->
      <path
        ref="blackPathRef"
        :d="props.pathOn"
        :style="{
          fill: 'none',
          stroke: themeBlack,
          strokeWidth: '12',
        }"
      />
      <!-- Red animated overlay -->
      <path
        ref="redPathRef"
        :d="props.pathOn"
        :style="{
          fill: 'none',
          stroke: themeRed,
          strokeWidth: '12',
        }"
      />
    </g>

    <g v-else>
      <!-- Red base path (underlay) -->
      <path
        ref="redPathRef"
        :d="props.pathOff"
        :style="{
          fill: 'none',
          stroke: themeRed,
          strokeWidth: '12',
        }"
      />
      <!-- Black animated overlay -->
      <path
        ref="blackPathRef"
        :d="props.pathOff"
        :style="{
          fill: 'none',
          stroke: themeBlack,
          strokeWidth: '12',
        }"
      />
    </g>
  </svg>
</template>
