// vue/tech-course-graphics/src/components/computer/TransistorCircuitChip.vue
<script setup lang="ts">
import { ref } from 'vue'
import Wire from '../items/Wire.vue'
import { PathBuilder } from '../../utils/path'
import Transistor from '../items/Transistor.vue'
import Chip from '../items/Chip.vue'

const props = defineProps<{
  height: number
  width: number
}>()

const isOn = ref(false)

const wirePathMain = new PathBuilder(props.width, props.height, props.width * 0.1, props.height * 0.7, 10)
  .diag(1, 1)
  .right(6)
  .diag(1, -1)
  .build()

const wirePathOn = new PathBuilder(props.width, props.height, props.width * 0.6, props.height * 0.55, 10)
  .diag(-1, 2)
  .left(1)
  .up(0.3)
  .left(1)
  .down(0.3)
  .left(1)
  .diag(-1, -1)
  .build()

const wirePathOff = new PathBuilder(props.width, props.height, props.width * 0.6, props.height * 0.55, 10)
  .diag(-1, 2)
  .left(1)
  .up(0.3)
  .diag(-1, 0.7)
  .skip(0, -1)
  .left(1)
  .diag(-1, -1)
  .build()

</script>

<template>
  <div>
    <svg
      :height="props.height"
      :width="props.width"
      xmlns="http://www.w3.org/2000/svg"
      overflow="visible"
      @click="isOn = !isOn"
    >
      <Chip
        :height="props.height"
        :width="props.width"
      />
      <Wire
        :pathOn="wirePathMain"
        :pathOff="wirePathMain"
        :isOn="isOn"
        :circleStart="true"
        :circleEnd="true"
      />
      <Wire
        :pathOn="wirePathOn"
        :pathOff="wirePathOff"
        :isOn="isOn"
        :circleEnd="true"
      />
      <Transistor
        :height="80"
        :width="210"
        :x="props.width*0.6"
        :y="props.height*0.6"
      ></Transistor>
    </svg>
  </div>
</template>

// src/views/TransistorCircuitChip.tsx
import { useState } from 'react'
import { Wire } from '../items/Wire'
import Transistor from '../items/Transistor'
import Chip from '../items/Chip'
import { wireChipConnectorColor } from '../constants'

function TransistorCircuitChip() {

  const height = 400
  const width = 1000

  const [wireOn, setWireOn] = useState(false)

  const pathOff = `
    M ${width * 6.5 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 5 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 4 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 4 / 10} ${height * 2.5 / 10} ${''/* bottom left */}
    L ${width * 3 / 10} ${height * 1.5 / 10} ${''/* bottom left */}
    M ${width * 3 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 2 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 1 / 10} ${height * 4 / 10} ${''/* Start bottom middle */}  
  `
  const pathOn = `
    M ${width * 6.5 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 5 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 4 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 4 / 10} ${height * 2.5 / 10} ${''/* bottom left */}
    L ${width * 3 / 10} ${height * 2.5 / 10} ${''/* bottom left */}
    L ${width * 3 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 2 / 10} ${height * 3 / 10} ${''/* bottom left */}
    L ${width * 1 / 10} ${height * 4 / 10} ${''/* Start bottom middle */}  
  `
  const pathOff2 = `
    M ${width * 1 / 10} ${height * 7 / 10} ${''/* Start bottom middle */}
    L ${width * 2 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 8 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 9 / 10} ${height * 7 / 10} ${''/* bottom left */}
  `
  const pathOn2 = `
    M ${width * 1 / 10} ${height * 7 / 10} ${''/* Start bottom middle */}
    L ${width * 2 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 8 / 10} ${height * 6 / 10} ${''/* bottom left */}
    L ${width * 9 / 10} ${height * 7 / 10} ${''/* bottom left */}
  `

  return (
    <div>
      <svg height={height} width={width} xmlns="http://www.w3.org/2000/svg" overflow={'visible'}>
        <Chip width={width} height={height} />
        {/* Wires */}
        <Wire
          pathOn={pathOn}
          pathOff={pathOff}
          wireOn={wireOn}
          onClickFn={() => setWireOn(!wireOn)}
        ></Wire>
        <Wire
          pathOn={pathOn2}
          pathOff={pathOff2}
          wireOn={wireOn}
          onClickFn={() => setWireOn(!wireOn)}
        ></Wire>
        {/* Other Items */}
        <Transistor height={80} width={200} x={width * 5 / 10} xinner={width * 5.7 / 10} y={height * 5 / 10}></Transistor>
        <circle fill={wireChipConnectorColor} cx={width * 1 / 10} cy={height * 4 / 10} r={10}></circle>
        <circle fill={wireChipConnectorColor} cx={width * 1 / 10} cy={height * 7 / 10} r={10}></circle>
        <circle fill={wireChipConnectorColor} cx={width * 9 / 10} cy={height * 7 / 10} r={10}></circle>
      </svg>
    </div>
  )
}
  
export default TransistorCircuitChip
